receivers:
  otlp:
    protocols:
      grpc:
        # Need to make sure we bind to the host's localhost
        endpoint: 0.0.0.0:4317

  prometheus:
    config:
      scrape_configs:
      - job_name: 'otelcol'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '.*grpc_io.*'
            action: drop

processors:
  resource:
    attributes:
    # Must add a location here – this doesn't mean anything but must be one of the real GCP 
    # regions.
    - key: "location"
      value: "us-west2"
      action: upsert

  batch:
    # batch metrics before sending to reduce API usage
    send_batch_max_size: 200
    send_batch_size: 200
    timeout: 5s

  memory_limiter:
    # drop metrics if memory usage gets too high
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

exporters:
  googlemanagedprometheus:

  debug:
    verbosity:
      detailed
      
extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
#  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [resource, batch, memory_limiter]
      exporters: [googlemanagedprometheus]
#      exporters: [debug]
